// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANO43bFHamE-jbB8NA099ms_B8Y8e4k9U',
    appId: '1:481852256090:web:5fa03bdd1082eb64b34d63',
    messagingSenderId: '481852256090',
    projectId: 'sportify-86aa2',
    authDomain: 'sportify-86aa2.firebaseapp.com',
    storageBucket: 'sportify-86aa2.firebasestorage.app',
    measurementId: 'G-2E6HK2DX5V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYTKsOD_J3_xyr2o0xL5mpsdAFH_h4-Us',
    appId: '1:481852256090:android:6bb0725de9e2fad9b34d63',
    messagingSenderId: '481852256090',
    projectId: 'sportify-86aa2',
    storageBucket: 'sportify-86aa2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJnornjj_pOMefENI5emmgesk2dI6AQo0',
    appId: '1:481852256090:ios:36f7ac48239e2e76b34d63',
    messagingSenderId: '481852256090',
    projectId: 'sportify-86aa2',
    storageBucket: 'sportify-86aa2.firebasestorage.app',
    iosBundleId: 'com.example.mainScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJnornjj_pOMefENI5emmgesk2dI6AQo0',
    appId: '1:481852256090:ios:36f7ac48239e2e76b34d63',
    messagingSenderId: '481852256090',
    projectId: 'sportify-86aa2',
    storageBucket: 'sportify-86aa2.firebasestorage.app',
    iosBundleId: 'com.example.mainScreen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANO43bFHamE-jbB8NA099ms_B8Y8e4k9U',
    appId: '1:481852256090:web:7b447e5dc7f98ef8b34d63',
    messagingSenderId: '481852256090',
    projectId: 'sportify-86aa2',
    authDomain: 'sportify-86aa2.firebaseapp.com',
    storageBucket: 'sportify-86aa2.firebasestorage.app',
    measurementId: 'G-WMRXZJ7ZWE',
  );
}
